apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: author-deployment
  annotations:
    argocd/app-name: dev-notification-service
    backstage.io/kubernetes-namespace: test
    backstage.io/kubernetes-id: author-deployment
  description: Demo for the 2022 Planview Hackathon
  tags:
    - python
    - data
    - hackathon
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: Team Atlas
  system: pv-core-services
  dependsOn: ['resource:teamtap-db']
  apiConsumedBy: ['component:planview-core-services']
